### Link : https://www.worldometers.info/world-population/population-by-country/

In [1]:
# Import Required Dependencies
import requests
from bs4 import BeautifulSoup
import pandas as pd
# Page Url
url = 'https://www.worldometers.info/world-population/population-by-country/'

# send the request
html_text = requests.get(url)

# scraping the whole content of the page
soup = BeautifulSoup(html_text.content, 'html.parser')

titles = []

# scraping the table headers
headings = soup.find('thead')
for title in headings.tr.find_all('th'):
    titles.append(title.text)

data = dict()

for i in titles:
    if i not in data.keys():
        data[i] = []

keys = list(data.keys())
for i in soup.find('tbody').find_all('tr'):
    for index,j in enumerate(i.find_all('td')):
        data[keys[index]].append(j.text)

# Loading the data into pandas dataframe
population_by_counrty = pd.DataFrame(data)
population_by_counrty.drop('#', axis=1, inplace = True)

# saving the Dataframe to csv file 
population_by_counrty.to_csv('population by world.csv', index = False)

,Country (or dependency),Population (2020),Yearly Change,Net Change,Density (P/Km²),Land Area (Km²),Migrants (net),Fert. Rate,Med. Age,Urban Pop %,World Share
0,Honduras,"9,904,607",1.63 %,"158,490",89,"111,890","-6,800",2.5,24,57 %,0.13 %
1,United Arab Emirates,"9,890,402",1.23 %,"119,873",118,"83,600","40,000",1.4,33,86 %,0.13 %
2,Djibouti,"988,000",1.48 %,"14,440",43,"23,180",900,2.8,27,79 %,0.01 %
3,Saint Barthelemy,"9,877",0.30 %,30,470,21,,N.A.,N.A.,0 %,0.00 %
4,Seychelles,"98,347",0.62 %,608,214,460,-200,2.5,34,56 %,0.00 %
...,...,...,...,...,...,...,...,...,...,...,...
230,Jordan,"10,203,134",1.00 %,"101,440",115,"88,780","10,220",2.8,24,91 %,0.13 %
231,Portugal,"10,196,709",-0.29 %,"-29,478",111,"91,590","-6,000",1.3,46,66 %,0.13 %
232,Azerbaijan,"10,139,177",0.91 %,"91,459",123,"82,658","1,200",2.1,32,56 %,0.13 %
233,Sweden,"10,099,265",0.63 %,"62,886",25,"410,340","40,000",1.9,41,88 %,0.13 %
234,India,0,-100.00 %,"-1,366,417,754",0,"2,973,190","-532,687",2.2,28,N.A.,0.00 %